      <div class="contenido_margen"></div>
<div class="contenido_titulo">{TR|o_nombre}</div>
<div class="contenido_7">{PL|nombre} </div>
<div class="contenido_separador"></div>
<div class="contenido_margen"></div>
<div class="contenido_titulo">{TR|o_apellido}</div>
<div class="contenido_7">{PL|apellido} </div>
<div class="contenido_separador"></div>
<div class="contenido_margen"></div>
<div class="contenido_titulo">{TR|o_mail}</div>
<div class="contenido_7">{PL|mail} </div>
<div class="contenido_separador"></div>
<div class="contenido_margen"></div>
<div class="contenido_titulo">{TR|o_telefono}</div>
<div class="contenido_7">{PL|telefono} </div>
<div class="contenido_separador"></div>
<div class="contenido_margen"></div>
<div class="contenido_titulo">{TR|o_habilitado}</div>
<div class="contenido_7">{PL|habilitado} </div>
<div class="contenido_margen"></div>
<div class="contenido_solo_titulo">{TR|o_roles}</div>
<div class="contenido_separador"></div>